<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InfluxDB.Client" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pulswerk.Core\Pulswerk.Core.csproj" />
  </ItemGroup>

</Project>
